In [ ]:
Case E-commerce Olist

Instalando bibliotecas

In [1]:
%pip install pandas
%pip install ipykernel
%pip install matplotlib
%pip install seaborn
%pip install openpyxl

Requirement already satisfied: pandas in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: ipykernel in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (7.4.0)
Requirement already satisfied: comm>=0.1.1 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (1.8.22)
Requirement already satisfied: ipython>=7.23.1 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (9.17.1)
Requirement already satisfied: jupyter-client>=8.9.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (8.10.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (1.7.4)
Requirement already satisfied: packaging>=22 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (26.3)
Requirement already satisfied: pyzmq>=25 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (27.2.0)
Requirement already satisfied: tornado>=6.5.7 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (6.5.10)
Requirement already satisfied: traitlets>=5.4.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipykernel) (5.16.1)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.20.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.53)
Requirement already satisfied: psutil>=7 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.9.2)
Requirement already satisfied: parso<0.9.0,>=0.8.7 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from jupyter-client>=8.9.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.13.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from jupyter-client>=8.9.0->ipykernel) (4.16.0)
Requirement already satisfied: platformdirs>=2.5 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.13.2)
Requirement already satisfied: six>=1.5 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.9.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.3.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.2)
Requirement already satisfied: pure-eval in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.4)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib) (2.5.4)
Requirement already satisfied: packaging>=20.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from seaborn) (2.5.4)
Requirement already satisfied: pandas>=1.2 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from seaborn) (3.0.6)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from seaborn) (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from pandas>=1.2->seaborn) (2026.5)
Requirement already satisfied: six>=1.5 in c:\Users\diego\OneDrive\Pós Graduação FIAP - Data Analytics\Tech Challenge - Fase 01\Dados\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None)': /simple/openpyxl/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None)': /simple/openpyxl/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None)': /simple/openpyxl/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None)': /simple/openpyxl/
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None)': /packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl.metadata

In [1]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Importando as bibliotecas necessárias
import os
import pandas as pd

In [4]:
# Definindo o caminho para a pasta de dados
DATA_PATH = os.path.join("..", "data")

In [6]:
# Carregando as 3 bases principais do Olist
orders = pd.read_csv(os.path.join(DATA_PATH, "olist_orders_dataset.csv"))
items = pd.read_csv(os.path.join(DATA_PATH, "olist_order_items_dataset.csv"))
payments = pd.read_csv(os.path.join(DATA_PATH, "olist_order_payments_dataset.csv"))
print("Arquivos carregados com sucesso!")

Arquivos carregados com sucesso!

Explorando a tabela dos pedidos e datas

In [7]:
# 1. Dimensões do DataFrame (quantas linhas e quantas colunas existem)
print("Dimensões da base orders:", orders.shape)

# 2. Exibir as 5 primeiras linhas para entender a estrutura dos dados
orders.head()

Dimensões da base orders: (99441, 8)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
# Contar quantos pedidos existem por cada status de pedido (order_status)
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [9]:
# Informações técnicas sobre as colunas, tipos e valores não nulos
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [10]:
# Lista com o nome de todas as colunas que guardam datas
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

# Convertendo cada uma delas de texto para o formato datetime
for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

# Conferindo se os tipos mudaram
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

Explorando a tabela de itens

In [11]:
# 1. Dimensões da base items
print("Dimensões da base items:", items.shape)

# 2. Visualizar as 5 primeiras linhas
items.head()

Dimensões da base items: (112650, 7)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [12]:
# 1. Resumo estatístico das colunas numéricas
items[['price', 'freight_value']].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

Unindo as duas tabelas com os pedidos efetivamente entregues

In [13]:
# Cruzamento da tabela de pedidos com a tabela de itens através da chave comum 'order_id'
df_orders_items = pd.merge(
    left=orders, 
    right=items, 
    on='order_id', 
    how='inner'
)

# Verificar as dimensões da nova tabela combinada
print("Dimensões após o cruzamento:", df_orders_items.shape)

# Pré-visualizar as primeiras 3 linhas
df_orders_items.head(3)

Dimensões após o cruzamento: (112650, 14)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22

In [14]:
# Filtrando apenas os pedidos que foram efetivamente entregues
df_delivered = df_orders_items[df_orders_items['order_status'] == 'delivered'].copy()

# Verificando a redução do volume
print("Dimensões com pedidos entregues:", df_delivered.shape)

Dimensões com pedidos entregues: (110197, 14)

Visão mensal de compras (Ano-Mês)